# Generated by Django 5.0.3 on 2024-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_title', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('task_desc', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
