# Generated by Django 5.0.3 on 2024-05-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbybit', '0002_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
