# Generated by Django 5.0.3 on 2024-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbybit', '0005_task_task_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_index',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
