# Generated by Django 5.0.3 on 2024-05-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbybit', '0008_alter_task_task_index_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=70),
        ),
    ]
