# Generated by Django 5.0.3 on 2024-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbybit', '0009_alter_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
